# Generated by Django 6.0.4 on 2026-05-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.IntegerField(default=2023, max_length=4),
            preserve_default=False,
        ),
    ]
